name: Repository Dispatch
on:
  repository_dispatch:
    types: [sfdx-deploy]
jobs:
  sfdxDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        if: github.event.client_payload.PRIVATE_KEY != ''
        uses: actions/checkout@v2

      - name: Change to repo directory
        run: cd ChatBotModel || echo "Can't cd into ChatBotModel"
        if: github.event.client_payload.PRIVATE_KEY != ''

      - name: Install Salesforce CLI
        run: |
          echo pwd
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
          rm sfdx-linux-x64.tar.xz
          git fetch --unshallow
        if: github.event.client_payload.PRIVATE_KEY != ''

      - name: JWT Private Key
        run: echo "${{ github.event.client_payload.PRIVATE_KEY }}" > ~/sfdx/server.key
        if: github.event.client_payload.PRIVATE_KEY != ''

      - name: 'Authenticate SF Org and Functions Account'
        run: ~/sfdx/bin/sfdx force:auth:jwt:grant -u test-8jnql1hxecqa@example.com -f C:\Users\naresh.kaneria\Desktop\JWT\server.key -i 3MVG9e2mBbZnmM6mZipb2bHuql9JEuwP404QpS3uSKAK3trOQ2bgkAWSfeNOVmyk2cJfQjc2qQcuzy6s5rOOL -r https://velocity-platform-6796-dev-ed.cs6.my.salesforce.com/

        if: github.event.client_payload.PRIVATE_KEY != ''

      - name: 'Create compute environment for the functions'
        run: ~/sfdx/bin/sf env create compute --connected-org=functionv4 --alias=lmo_func_env     
        if: github.event.client_payload.PRIVATE_KEY != ''

      - name: 'Deploy functions to connected org'
        run: ~/sfdx/bin/sfdx deploy:functions -o functionv4
        if: github.event.client_payload.PRIVATE_KEY != ''
